### ISSUE TITLE
Can't connect to any sonoff devices

### ISSUE THREAD

**Issue by susadmin** [tprelog/iocage-tasmoadmin#3]
Hi, I have installed your plugin on my FreeNAS 11.3-U2 server but it won't connect to any of my sonoff devices. If I do a search from the web interface, I get a curl 28 error. 

Interestingly, if I go to the console of the jail, I can ping my router and other devices on the network but not my sonoff devices. Do you have any ideas? I would be happy to send some config/logs if that would help.

Thanks

**Comment by tprelog** [comment]
I assume you did flash [Tasmota](https://tasmota.github.io/docs/) and have completed the [initial configuration](https://tasmota.github.io/docs/Getting-Started/#initial-configuration) ( at least connect to your WiFi.

After adding to your WiFi, are you able to directly reach the Tasmotized Sonoff devices WebUI from another computer or phone?

Are you able to add the device to TasmoAdmin is you specify using the device IP Address?

I see some open issue filed in TasmoAdmin repo related to curl 28 error and the auto scan not working, I wonder if your issue is related to something here ? https://github.com/reloxx13/TasmoAdmin/issues?q=is%3Aissue+is%3Aopen+curl

It's been awhile since I've messed with anything related to Tasmota ( That's a good thing because I set them up once and they're still working ) During this coming week, I will try and make time to further investigate if I reproduce your troubles on my setup.
